### ISSUE TITLE
Go through and consistently remove Specs from namespace for specs

### ISSUE THREAD

**Issue by einari** [dolittle/Home#33]
The namespace should match the System Under Test - we don't need the added "specs" part. This complicates things when we have sub-namespaces. 

Projects affected:

- [x] .NET SDK
- [ ] .NET Fundamentals
- [ ] Runtime
- [ ] AspNetCore
- [ ] AutoFac
- [ ] EventStore specs
- [ ] Geodesics specs
- [ ] EventSubscriberOffsets specs

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1115620408084369)

**Comment by woksin** [comment]
I can run through the SDK repo.

So we should just remove all the Specs segments from namespaces?

**Comment by einari** [comment]
Great. 
That means we'll have the "for_*" namespaces in parallel to the namespaces or the unit it is specifying.

E.g.:

Dolittle.Commands

Would have Command Coordinator and also a namespaces called 'for_CommandCoordinator'
