### ISSUE TITLE
Create JSON Schemas for all our configuration files

### ISSUE THREAD

**Issue by einari** [dolittle/Home#35]
- [x] Event Horizon
- [x] Tenants
- [x] Tenant Maps
- [x] Topology
- [x] Artifacts
- [x] Server
- [x] Resources
- [x] Bounded Context
- [ ] Application
- [ ] Dolittle RC
- [ ] Dolittle Tooling config - config.json
- [ ] Dolittle Tooling - Boilerplates config

We should adhere to the schema standard: http://json-schema.org

All schemas should be published and versioned here:
http://schemastore.org/json/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1115620406771600)

**Comment by woksin** [comment]
Most of the schemas are done and in PRs, the only framework related schema remaining is application.json.
