### ISSUE TITLE
QuickStart document calls CLI command that is no longer available

### ISSUE THREAD

**Issue by TonyHernandezAtMS** [dolittle/Home#56]
https://dolittle.io/getting-started/quickstart/

4) Build and Run the Template Application
To run the application, we will use the Dolittle CLI tool again. From the TodoTracking folder, run the following command.

dolittle run
No such command, command group or namespace 'run'

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1146548723585605)

**Comment by einari** [comment]
Thanks for pointing this out, its a feature we forgot to include when we rewrote our CLI code to TypeScript.

Basically what the `run` command effectively did was to automatically call the `dotnet watch run` command on the `Core` project and then run `yarn start` from the Web folder.

In addition it also started a Mongo database using Docker. So if you do that in advance:

```shell
$ docker run -p 27017:27017 mongo
```

There is a `run.js` file in the boilerplate that gets you going. It uses ASP.NET Core as the static web server as well and will make WebPack output its things into the `wwwroot` in the `Core` project.

If you want to run the `Core`project as one process and the `Web` as one, I see that there are some things missing from the boilerplate for it to effectively work with running two processes - to avoid CORS issues. I've registered an issue for us to fix that in the boilerplate:
https://github.com/dolittle-boilerplates/Interaction.Web.JS.Aurelia/issues/14

We have encountered the last week a breaking change related to Bluebird and promises for the Web part using Aurelia, we have a thread going over here:

https://community.dolittle.com/t/aurelia-frontend-module-not-found-error-cant-resolve-async-hooks-in-bluebirdjs/37


There are new debugging / Swagger extensions we've built for ASP.NET Core as well that will help you work with Commands and Events, you can read more about that [here](https://dolittle.io/interaction/aspnetcore/aspnetcore-debugging-swagger/).
