### ISSUE TITLE
Booting fails when the Logger is set to Serilog and the Verbose logging level is selected

### ISSUE THREAD

**Issue by smithmx** [dolittle/Home#83]
https://github.com/dolittle-fundamentals/DotNET.Fundamentals/blob/adec777895b23e35152e677ee94c723a6c9a741c/Source/Logging/Booting/BootLogMessageWriterCreator.cs#L42

In an ASPNET.Core app, configuring Serilog as the logger via the Microsoft.Extensions.Logger interfact works until you choose "Verbose" as the logging level.  Microsoft uses "Trace" instead.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159865615645745/1175096265574678)

**Comment by jakhog** [comment]
This issue has been fixed in https://github.com/dolittle-fundamentals/DotNET.Fundamentals/pull/319 and will be a part of the upcoming 5.0.0 release.
